version: '3'
services:
  strapi:
    container_name: strapi2
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=127.0.0.1
      - DATABASE_PORT=27017
      - DATABASE_NAME=speculor-website
      - DATABASE_USERNAME=mongo_admin
      - DATABASE_PASSWORD=REDACTED
      - AUTHENTICATION_DATABASE=strapi
    volumes:
      - ./app:/srv/app
    network_mode: host
    restart: always

